version: '3'
services:
  db:
    image: mysql:8.0.40
    restart: always
    container_name: db
    environment:
      - MYSQL_DATABASE=investments
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://root:Galadriel123@db:3306/investments"
    depends_on:
      - db
    command: bash -c "npx prisma migrate dev --name init && npm run dev"

volumes:
  db_data:
