services:
  db:
    image: mysql:8.0.40
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://root:Galadriel123%40@localhost:3306/investments"
    depends_on:
      - db
    # volumes:
    #   # - ./backend:/app
    #   # - /app/node_modules

volumes:
  db_data:
